# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  paging:
    pager: BAT_THEME="${CONFIG_COLORS}" DELTA_FEATURES="+${CONFIG_COLORS_MODE}" delta --paging never
    colorArg: always
