#!usr/bin/env sh

if [[ $1 == "-h" || $1 == "--help" ]]; then
	print "Set terminal theme"
	return 0
fi

if [[ "${TERM}" == "xterm-kitty" ]]; then
	set -euo pipefail

	local themes_dir="${XDG_CONFIG_HOME}/kitty/themes"
	kitty @ set-colors -c "${themes_dir}/$1.conf"
	kitty @ env CONFIG_COLORS"$1"
	export CONFIG_COLORS=$1
	return 0
fi

if [[ "${TERM}" == "wezterm" ]]; then
	printf "\033]1337;SetUserVar=%s=%s\007" "CONFIG_COLORS" $(echo -n "$1" | base64)
	export CONFIG_COLORS=$1
	return 0
fi

print "Not in supported terminal"
return 1
