#!usr/bin/env sh

if [[ "${TERM}" != "xterm-kitty" ]]; then
	print "Not in supported terminal"
	return 1
fi

if [[ $1 == "-h" || $1 == "--help" ]]; then
	print "TODO: show usage"
	return 0
fi

local themes_dir="${XDG_CONFIG_HOME}/kitty/themes"

kitty @ set-colors -c "${themes_dir}/$1.conf"
kitty @ env "$1"

if [[ $? != 0 ]]; then
	return 2
fi

# set environment variable after the above succeeds
export CONFIG_COLORS=$1
