local conf="${XDG_CONFIG_HOME}/zsh"
local init="${conf}/init"

# TODO: check if Homebrew is installed before exporting
export HOMEBREW_PREFIX="$(brew --prefix)"

# initialize prompt first
source "${init}/prompt.zsh"

source "${init}/path.zsh"			# add executables to $PATH
source "${init}/options.zsh"		# set options for interactive shells
source "${init}/completion.zsh"		# shell autocomplete; update dumpfile
source "${init}/variables.zsh"		# env vars for CLI tools
source "${init}/aliases.zsh"

# add shell functions
fpath+="${conf}/functions"
# autoload all functions found in the directory
autoload ${fpath[-1]}/*(:t)

# bun completions
[ -s "/usr/local/Cellar/bun/0.6.13/share/zsh/site-functions/_bun" ] && source "/usr/local/Cellar/bun/0.6.13/share/zsh/site-functions/_bun"
