local conf="${XDG_CONFIG_HOME}/zsh"
local init="${conf}/init"

# initialize prompt first
source "${init}/prompt.zsh"

source "${init}/variables.zsh"		# env vars for CLI tools
source "${init}/path.zsh"			# add executables to $PATH
source "${init}/options.zsh"		# set options for interactive shells
source "${init}/completion.zsh"		# shell autocomplete; update dumpfile
source "${init}/fzf.zsh"			# CLI fuzzy finder
source "${init}/aliases.zsh"

# add shell functions
fpath+="${conf}/functions"
# autoload all functions found in the directory
autoload ${fpath[-1]}/*(:t)
